"""empty message

Revision ID: 412752508848
Revises: 5d07c1802499
Create Date: 2024-05-27 20:42:36.843342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '412752508848'
down_revision = '5d07c1802499'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cosmic_encounter_game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('winnerName', sa.String(length=50), nullable=False),
    sa.Column('winnerScore', sa.Integer(), nullable=False),
    sa.Column('secondName', sa.String(length=50), nullable=False),
    sa.Column('secondScore', sa.Integer(), nullable=False),
    sa.Column('thirdName', sa.String(length=50), nullable=False),
    sa.Column('thirdScore', sa.Integer(), nullable=False),
    sa.Column('fourthName', sa.String(length=50), nullable=True),
    sa.Column('fourthScore', sa.Integer(), nullable=True),
    sa.Column('fifthName', sa.String(length=50), nullable=True),
    sa.Column('fifthScore', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coup_game', schema=None) as batch_op:
        batch_op.drop_column('cardsLeft')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coup_game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cardsLeft', sa.INTEGER(), nullable=False))

    op.drop_table('cosmic_encounter_game')
    # ### end Alembic commands ###
