"""Initial Migration

Revision ID: 5d07c1802499
Revises: 
Create Date: 2024-05-27 16:51:21.917959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d07c1802499'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clank_game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('winnerName', sa.String(length=50), nullable=False),
    sa.Column('winnerScore', sa.Integer(), nullable=False),
    sa.Column('secondName', sa.String(length=50), nullable=False),
    sa.Column('secondScore', sa.Integer(), nullable=False),
    sa.Column('thirdName', sa.String(length=50), nullable=True),
    sa.Column('thirdScore', sa.Integer(), nullable=True),
    sa.Column('fourthName', sa.String(length=50), nullable=True),
    sa.Column('fourthScore', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cosmic_encounter_game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('winnerName', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('winnerScore', sa.Integer(), nullable=False))
        batch_op.drop_column('firstScore')
        batch_op.drop_column('firstName')

    with op.batch_alter_table('coup_game', schema=None) as batch_op:
        batch_op.drop_column('cardsLeft')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coup_game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cardsLeft', sa.INTEGER(), nullable=False))

    with op.batch_alter_table('cosmic_encounter_game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firstName', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('firstScore', sa.INTEGER(), nullable=False))
        batch_op.drop_column('winnerScore')
        batch_op.drop_column('winnerName')

    op.drop_table('clank_game')
    # ### end Alembic commands ###
