"""Exploding and Sushi

Revision ID: a5f75a21bf82
Revises: 412752508848
Create Date: 2024-05-27 20:54:29.882748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5f75a21bf82'
down_revision = '412752508848'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exploding_kittens_game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('winnerName', sa.String(length=50), nullable=False),
    sa.Column('secondName', sa.String(length=50), nullable=False),
    sa.Column('thirdName', sa.String(length=50), nullable=True),
    sa.Column('fourthName', sa.String(length=50), nullable=True),
    sa.Column('fifthName', sa.String(length=50), nullable=True),
    sa.Column('sixthName', sa.String(length=50), nullable=True),
    sa.Column('seventhName', sa.String(length=50), nullable=True),
    sa.Column('eighthName', sa.String(length=50), nullable=True),
    sa.Column('ninthName', sa.String(length=50), nullable=True),
    sa.Column('tenthName', sa.String(length=50), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sushi_go_party_game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('winnerName', sa.String(length=50), nullable=False),
    sa.Column('winnerScore', sa.Integer(), nullable=False),
    sa.Column('secondName', sa.String(length=50), nullable=False),
    sa.Column('secondScore', sa.Integer(), nullable=False),
    sa.Column('thirdName', sa.String(length=50), nullable=True),
    sa.Column('thirdScore', sa.Integer(), nullable=True),
    sa.Column('fourthName', sa.String(length=50), nullable=True),
    sa.Column('fourthScore', sa.Integer(), nullable=True),
    sa.Column('fifthName', sa.String(length=50), nullable=True),
    sa.Column('fifthScore', sa.Integer(), nullable=True),
    sa.Column('sixthName', sa.String(length=50), nullable=True),
    sa.Column('sixthScore', sa.Integer(), nullable=True),
    sa.Column('seventhName', sa.String(length=50), nullable=True),
    sa.Column('seventhScore', sa.Integer(), nullable=True),
    sa.Column('eighthName', sa.String(length=50), nullable=True),
    sa.Column('eighthScore', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sushi_go_party_game')
    op.drop_table('exploding_kittens_game')
    # ### end Alembic commands ###
